Name Changes.

diff --git a/post-receive b/post-receive
--- a/post-receive
+++ b/post-receive
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # Set up environment
-source ~/bin/philomena-env
+source ~/bin/ineedthis-env
 
 read oldrev newrev ref
 echo "Updating $oldrev -> $newrev ($ref)"
@@ -9,7 +9,7 @@ echo "Updating $oldrev -> $newrev ($ref)"
 # Clear variable set to '.' so git commands don't complain
 unset GIT_DIR
 
-cd ~/philomena
+cd ~/ineedthis
 
 die() {
     echo "$*" 1>&2
@@ -35,7 +35,7 @@ mix release --overwrite || die "failed to generate release"
 # Run migrations
 if git diff --name-only $oldrev $newrev | grep "^priv/repo/migrations"; then
   echo "Running database migrations"
-  _build/prod/rel/philomena/bin/philomena eval "Philomena.Release.migrate()" || die "ecto.migrate failed"
+  _build/prod/rel/ineedthis/bin/ineedthis eval "Ineedthis.Release.migrate()" || die "ecto.migrate failed"
 fi
 
 # Include a task to restart your running appserver instances here.
